// Code generated by go-bluetooth generator DO NOT EDIT.

package profile

import (
	"github.com/godbus/dbus/v5"
)

var (
	// InvalidArguments map to org.bluez.Error.InvalidArguments
	ErrInvalidArguments = dbus.Error{
		Name: "org.bluez.Error.InvalidArguments",
		Body: []interface{}{"InvalidArguments"},
	}
	// NotConnected map to org.bluez.Error.NotConnected
	ErrNotConnected = dbus.Error{
		Name: "org.bluez.Error.NotConnected",
		Body: []interface{}{"NotConnected"},
	}
	// NotAcquired map to org.bluez.Error.NotAcquired
	ErrNotAcquired = dbus.Error{
		Name: "org.bluez.Error.NotAcquired",
		Body: []interface{}{"NotAcquired"},
	}
	// NotReady map to org.bluez.Error.NotReady
	ErrNotReady = dbus.Error{
		Name: "org.bluez.Error.NotReady",
		Body: []interface{}{"NotReady"},
	}
	// Failed map to org.bluez.Error.Failed
	ErrFailed = dbus.Error{
		Name: "org.bluez.Error.Failed",
		Body: []interface{}{"Failed"},
	}
	// AlreadyExists map to org.bluez.Error.AlreadyExists
	ErrAlreadyExists = dbus.Error{
		Name: "org.bluez.Error.AlreadyExists",
		Body: []interface{}{"AlreadyExists"},
	}
	// NotSupported map to org.bluez.Error.NotSupported
	ErrNotSupported = dbus.Error{
		Name: "org.bluez.Error.NotSupported",
		Body: []interface{}{"NotSupported"},
	}
	// Rejected map to org.bluez.Error.Rejected
	ErrRejected = dbus.Error{
		Name: "org.bluez.Error.Rejected",
		Body: []interface{}{"Rejected"},
	}
	// InProgress map to org.bluez.Error.InProgress
	ErrInProgress = dbus.Error{
		Name: "org.bluez.Error.InProgress",
		Body: []interface{}{"InProgress"},
	}
	// NotAvailable map to org.bluez.Error.NotAvailable
	ErrNotAvailable = dbus.Error{
		Name: "org.bluez.Error.NotAvailable",
		Body: []interface{}{"NotAvailable"},
	}
	// AuthenticationCanceled map to org.bluez.Error.AuthenticationCanceled
	ErrAuthenticationCanceled = dbus.Error{
		Name: "org.bluez.Error.AuthenticationCanceled",
		Body: []interface{}{"AuthenticationCanceled"},
	}
	// AuthenticationFailed map to org.bluez.Error.AuthenticationFailed
	ErrAuthenticationFailed = dbus.Error{
		Name: "org.bluez.Error.AuthenticationFailed",
		Body: []interface{}{"AuthenticationFailed"},
	}
	// AuthenticationRejected map to org.bluez.Error.AuthenticationRejected
	ErrAuthenticationRejected = dbus.Error{
		Name: "org.bluez.Error.AuthenticationRejected",
		Body: []interface{}{"AuthenticationRejected"},
	}
	// AuthenticationTimeout map to org.bluez.Error.AuthenticationTimeout
	ErrAuthenticationTimeout = dbus.Error{
		Name: "org.bluez.Error.AuthenticationTimeout",
		Body: []interface{}{"AuthenticationTimeout"},
	}
	// ObexRejected map to org.bluez.obex.Error.Rejected
	ErrObexRejected = dbus.Error{
		Name: "org.bluez.obex.Error.Rejected",
		Body: []interface{}{"ObexRejected"},
	}
	// ObexInvalidArguments map to org.bluez.obex.Error.InvalidArguments
	ErrObexInvalidArguments = dbus.Error{
		Name: "org.bluez.obex.Error.InvalidArguments",
		Body: []interface{}{"ObexInvalidArguments"},
	}
	// ObexForbidden map to org.bluez.obex.Error.Forbidden
	ErrObexForbidden = dbus.Error{
		Name: "org.bluez.obex.Error.Forbidden",
		Body: []interface{}{"ObexForbidden"},
	}
	// ObexNotSupported map to org.bluez.obex.Error.NotSupported
	ErrObexNotSupported = dbus.Error{
		Name: "org.bluez.obex.Error.NotSupported",
		Body: []interface{}{"ObexNotSupported"},
	}
	// ObexNotAuthorized map to org.bluez.obex.Error.NotAuthorized
	ErrObexNotAuthorized = dbus.Error{
		Name: "org.bluez.obex.Error.NotAuthorized",
		Body: []interface{}{"ObexNotAuthorized"},
	}
	// ObexInProgress map to org.bluez.obex.Error.InProgress
	ErrObexInProgress = dbus.Error{
		Name: "org.bluez.obex.Error.InProgress",
		Body: []interface{}{"ObexInProgress"},
	}
	// ObexNotInProgress map to org.bluez.obex.Error.NotInProgress
	ErrObexNotInProgress = dbus.Error{
		Name: "org.bluez.obex.Error.NotInProgress",
		Body: []interface{}{"ObexNotInProgress"},
	}
)
