// Code generated by go-bluetooth generator DO NOT EDIT.

/*
BlueZ D-Bus AdminPolicySet API documentation [org.bluez.AdminPolicySet.rst]
This API provides methods to control the behavior of **bluetoothd(8)** as an
administrator.

Interface AdminPolicySet1 provides methods to set policies. Once the policy is
set successfully, it will affect all clients and stay persistently even after
restarting **bluetoothd(8)**. The only way to clear it is to overwrite the
policy with the same method.

Interface
=========

:Service:	org.bluez
:Interface:	org.bluez.AdminPolicySet1 [experimental]
:Object path:	[variable prefix]/{hci0,hci1,...}
*/
package admin_policy
