// Code generated by go-bluetooth generator DO NOT EDIT.

/*
BlueZ D-Bus LEAdvertisement API documentation [org.bluez.LEAdvertisement.rst]
Advertising packets are structured data which is broadcast on the LE Advertising
channels and available for all devices in range.  Because of the limited space
available in LE Advertising packets, each packet's contents must be carefully
controlled.

The service daemon acts as a store for the Advertisement Data which is meant to
be sent. It constructs the correct Advertisement Data from the structured
data and configured the kernel to send the correct advertisement.

Interface
=========

Specifies the Advertisement Data to be broadcast and some advertising
parameters.  Properties which are not present will not be included in the
data.  Required advertisement data types will always be included.
All UUIDs are 128-bit versions in the API, and 16 or 32-bit
versions of the same UUID will be used in the advertising data as appropriate.

:Service:	org.bluez
:Interface:	org.bluez.LEAdvertisement1
:Object path:	freely definable
*/
package advertising
