// Code generated by go-bluetooth generator DO NOT EDIT.

/*
BlueZ D-Bus GattCharacteristic API documentation [org.bluez.GattCharacteristic.rst]
GATT local/server and remote/client characteristic attribute representation
share the same high-level D-Bus API.

Local/Server refers to GATT based characteristics exported by a plugin or an
external application.

Remote/Client refers to GATT characteristics exported by the peer.

Interface
=========

Client
------

:Service:	org.bluez
:Interface:	org.bluez.GattCharacteristic1
:Object path:	[variable prefix]/{hci0,hci1,...}/dev_XX_XX_XX_XX_XX_XX/serviceXX/charYYYY

Server
------

:Service:	unique name
:Interface:	org.bluez.GattCharacteristic1
:Object path:	freely definable
*/
package gatt
