// Code generated by go-bluetooth generator DO NOT EDIT.

/*
BlueZ D-Bus AdvertisementMonitor API documentation [org.bluez.AdvertisementMonitor.rst]
This API allows an client to specify a job of monitoring advertisements by
registering the root of hierarchy and then exposing advertisement monitors
under the root with filtering conditions, thresholds of RSSI and timers
of RSSI thresholds.

Once a monitoring job is activated by **bluetoothd(8)**, the client can expect
to get notified on the targeted advertisements no matter if there is an ongoing
discovery session (see **StartDiscovery()** in **org.bluez.Adapter(5)**).

Interface
=========

:Service:	org.bluez
:Interface:	org.bluez.AdvertisementMonitor1 [experimental]
:Object path:	freely definable
*/
package advertisement_monitor
